### ISSUE TITLE
errors in eda prod logs

### ISSUE THREAD

**Issue by aurreco-uga** [VEuPathDB/EdaMergingService#18]
Apr 8,9 2024

-------------------------------

**mbiome**

subsetting

2024-04-08 19:54:20.455 [rid:a256563acbb54ae691fd7c6b07fbe62d] DEBUG PrometheusFilter:165 - Request end: GET /studies/auto_20240408195155_1y95-1 200

mergng

2024-04-08 19:54:22.100 [rid:a256563acbb54ae691fd7c6b07fbe62d] DEBUG ErrorMapper:72 - Caught Exception:
 jakarta.ws.rs.BadRequestException: {"keyedErrors":{},"validationLevel":"RUNNABLE","validationStatus":"FAILED","errors":["Output variables (columns) must be distinct.  Column 'MBIOTEMP_Source.EUPATH_0009253_Bacteria_Bacteroidota_Bacteroidia' is specified more than once."]}
        at org.veupathdb.service.eda.ms.ServiceExternal.processMergedTabularRequest(ServiceExternal.java:134) ~[service.jar:3.0.0]
        at org.veupathdb.service.eda.ms.ServiceInternal.postMergingInternalQuery(ServiceInternal.java:41) ~[service.jar:3.0.0]

-----------------------------------

**vectorbase**

subsetting

^[[m^[[36m2024-04-09 01:57:05.445 [rid:3df0301caaad42a6a342e2566d172ba9] DEBUG PrometheusFilter:165 - Request end: GET /studies 200

merging:

2024-04-09 01:57:05.219 [rid:3df0301caaad42a6a342e2566d172ba9] INFO  ClientUtil:70 - Will send following GET request to http://subsetting-internal:80/studies
2024-04-09 01:57:05.447 [rid:3df0301caaad42a6a342e2566d172ba9] WARN  ErrorMapper:70 - Caught Exception:
 java.lang.RuntimeException: com.fasterxml.jackson.databind.JsonMappingException: Index -631 out of bounds for length 13 (through reference chain: org.veupathdb.service.eda.generated.model.StudiesGetResponseImpl["studies"]->java.util.ArrayList[88]->org.veupathdb.service.eda.generated.model.APIStudyOverviewImpl["lastModified"])
        at org.gusdb.fgputil.functional.Functions.swallowAndGet(Functions.java:418) ~[service.jar:3.0.0]
        at org.veupathdb.service.eda.common.client.EdaSubsettingClient.getStudies(EdaSubsettingClient.java:40) ~[service.jar:3.0.0]
        at org.veupathdb.service.eda.common.client.EdaSubsettingClient.getStudy(EdaSubsettingClient.java:53) ~[service.jar:3.0.0]
        at org.veupathdb.service.eda.ms.core.request.RequestResources.<init>(RequestResources.java:47) ~[service.jar:3.0.0]

**Comment by ryanrdoherty** [comment]
@dmgaldi That first one could easily be spam.  Note it's coming in from the external service (though would still need to be authenticated, so maybe it's legit from a user script).

**Comment by dmgaldi** [comment]
Possible explanation for the second one is [here](https://stackoverflow.com/questions/42181523/jsonmappingexception-while-serializing-was-java-lang-arrayindexoutofboundsexc). It looks like SimpleDateFormat may have a race condition

**Comment by aurreco-uga** [comment]
the first , ". Column 'MBIOTEMP_Source.EUPATH_0009253_Bacteria_Bacteroidota_Bacteroidia' is specified more than once."]}"

this could be the bug WOjtek originated with his sortening var names algorythm.
JB/Jay will fix in 69.


i dont see much in logs on teh secon d error.. 
closing...
